### ISSUE TITLE
Add netcdf4 to optional dependencies for faster AMBER trajectory writing

### ISSUE THREAD

**Issue by etherealsunshine** [Genentech/beignet#97]
## Problem
MDAnalysis (used via biotite dependency chain) warns when netcdf4 isn't available for AMBER trajectory writing:
`WARNING:MDAnalysis.coordinates.AMBER:netCDF4 is not available. Writing AMBER ncdf files will be slow.`

## Proposed Solution
Add `netcdf4` to the existing `mdtraj` optional dependency group:

```toml
[project.optional-dependencies]
mdtraj = [
    "mdtraj",
    "netcdf4", 
```
This also came up in [lobster issue #110](https://github.com/prescient-design/lobster/issues/110)

Happy to submit a PR if this approach looks good!
